USE [master]
GO

/****** Object:  Database [Coelsa]    Script Date: 9/4/2021 11:15:56 ******/
CREATE DATABASE [Coelsa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Coelsa', FILENAME = N'C:\Coelsa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Coelsa_log', FILENAME = N'C:\Coelsa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Coelsa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Coelsa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Coelsa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Coelsa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Coelsa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Coelsa] SET ARITHABORT OFF 
GO

ALTER DATABASE [Coelsa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Coelsa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Coelsa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Coelsa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Coelsa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Coelsa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Coelsa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Coelsa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Coelsa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Coelsa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Coelsa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Coelsa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Coelsa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Coelsa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Coelsa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Coelsa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Coelsa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Coelsa] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Coelsa] SET  MULTI_USER 
GO

ALTER DATABASE [Coelsa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Coelsa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Coelsa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Coelsa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Coelsa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Coelsa] SET QUERY_STORE = OFF
GO

USE [Coelsa]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Coelsa] SET  READ_WRITE 
GO


CREATE TABLE [dbo].[Contacts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[Company] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[PhoneNumber] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO Contacts
SELECT "Nicolas", "Tarlao", "Company 1", "ntarlao@gmail.com", "+54 011 57397931"

INSERT INTO Contacts
SELECT "Nicolas 2", "Tarlao 2", "Company 2", "ntarlao2@gmail.com", "+54 011 57397931"